apiVersion: v1
kind: ConfigMap
metadata:
  name: linux-processamento-texto-lab-es
  namespace: girus
  labels:
    app: girus-lab-template
data:
  lab.yaml: |
    name: linux-processamento-texto-es
    title: "Processamento de Texto no Linux: grep, sed, awk"
    description: "Domine as ferramentas essenciais de manipulação de texto no Linux, aprendendo a buscar padrões com grep, editar fluxos de texto com sed e processar dados estruturados com awk. Este laboratorio guiado fornece uma base sólida para automação, análise de logs e administração de sistemas Linux através do processamento eficiente de texto."
    duration: 25m
    image: "linuxtips/girus-devops:0.1"
    tasks:
      - name: "Buscando Padrões com grep"
        description: "aprende a utilizar o grep para encontrar e filtrar texto por padrões, compreendendo suas principais opções e casos de uso para análise de archivos e logs."
        steps:
          - "O **grep** (Global Regular Expression Print) é uma das ferramentas mais impuertantes para processamento de texto no Linux. Ele permite buscar padrões específicos em archivos ou na saída de outros comandos, sendo fundamentalmente útil para administração de sistemas e análise de logs."
          - "O grep trabalha linha por linha, examinando cada uma para determinar se contém o padrão de busca especificado, exibindo apenas as linhas que correspondem ao critério."
          - "vamos comenzar creando un archivo de ejemplo para demonstrar as funcionalidades do grep:"
          - "`for i in "Linha 1 com a palavra linux" "Linha 2 sem a palavra" "Linha 3 com linux novamente" "LINHA 4 COM LINUX"; do echo $i >> archivo_ejemplo.txt; done`"
          - "Este comando cria un archivo chamado <code>archivo_ejemplo.txt</code> com 4 linhas diferentes. Usamos o operador de redirecionamento <code>></code> para enviar a saída do comando <code>cat</code> para o archivo, e o delimitador <code>EOL</code> (End Of Line) para indicar o início e fim do conteúdo."
          - "**Busca básica com grep:**"
          - "A forma mais simples de usar o grep é fornecer un padrão de busca e o nome do archivo:"
          - "`grep 'linux' archivo_ejemplo.txt`"
          - "Este comando mostrará apenas as linhas que contêm a palavra 'linux'. Observe que, por padrão, o grep é case-sensitive (sensível a maiúsculas/minúsculas), então 'linux' e 'LINUX' são tratados como padrões diferentes."
          - "**Ignorando case (maiúsculas/minúsculas):**"
          - "Para realizar uma busca que ignore diferenças entre maiúsculas e minúsculas, usamos a flag <code>-i</code> (insensitive):"
          - "`grep -i 'linux' archivo_ejemplo.txt`"
          - "Agora o grep exibirá todas as linhas que contêm 'linux', 'LINUX', 'Linux', ou qualquer variação de capitalização."
          - "**Contando ocorrências:**"
          - "Em vez de exibir as linhas correspondentes, podemos apenas contar quantas delas existem com a flag <code>-c</code> (count):"
          - "`grep -c -i 'linux' archivo_ejemplo.txt`"
          - "Este comando retornará <code>3</code>, indicando que três linhas contêm a palavra 'linux' (em qualquer capitalização)."
          - "**Buscas mais avançadas:**"
          - "O grep também permite buscas mais complexas usando expressões regulares. Por ejemplo, para encontrar linhas que começam com 'Linha':"
          - "`grep '^Linha' archivo_ejemplo.txt`"
          - "O caractere <code>^</code> é un metacaractere que representa o início de uma linha."
          - "Para encontrar linhas que terminam com 'novamente':"
          - "`grep 'novamente$' archivo_ejemplo.txt`"
          - "O caractere <code>$</code> representa o fim de uma linha."
          - "**Mostrando o contexto:**"
          - "Às vezes, é útil ver algumas linhas antes ou depois do resultado. Podemos usar as flags <code>-B</code> (before) e <code>-A</code> (after):"
          - "`grep -A 1 -B 1 'sem' archivo_ejemplo.txt`"
          - "Este comando mostrará a linha que contém 'sem', mais uma linha antes e uma depois, proporcionando contexto ao resultado."
        tips:
          - type: "info"
            title: "O poder do grep"
            content: "grep é extremamente útil para buscar informações em logs, archivos de configuração e saídas de outros comandos. Explore opções como -r (recursivo), -v (inverter busca), -n (número da linha)."
          - type: "tip"
            title: "Combinando grep com outros comandos"
            content: "grep é frequentemente usado com pipes (|) para filtrar a saída de outros comandos. Por ejemplo: `ps aux | grep nginx` para encontrar processos do Nginx em execução."
          - type: "warning"
            title: "Performance em archivos grandes"
            content: "Para buscas em archivos muito grandes, considere usar ferramentas mais específicas como `zgrep` para archivos comprimidos ou `ack`/`ag` que são otimizadas para buscas rápidas."
        validation:
          - command: "grep -c -i 'linux' archivo_ejemplo.txt"
            expectedOutput: "3"
            errorMessage: "O comando grep -c -i não retornou o número esperado de linhas. verifique se o archivo foi criado corretamente."

      - name: "Editando Fluxos com sed"
        description: "Compreenda como o sed (Stream Editor) pode ser usado para transformar texto usando substituições, deleções e outros tipos de manipulações em archivos ou fluxos de dados."
        steps:
          - "O **sed** (Stream Editor) é uma poderosa ferramenta de processamento de texto que permite transformar o conteúdo de un archivo ou fluxo de dados sem necessidade de abrir un editor interativo. O sed trabalha como un editor não-interativo que processa o texto linha por linha, aplicando as transformações especificadas."
          - "vamos continuar usando o archivo de ejemplo que criamos anteriormente para demonstrar as capacidades do sed:"
          - "**Substituição básica:**"
          - "A operação mais comun no sed é a substituição de texto usando o comando <code>s</code> (substitute):"
          - "`sed 's/linux/GIRUS/' archivo_ejemplo.txt`"
          - "Este comando substitui a primeira ocorrência de 'linux' por 'GIRUS' em cada linha do archivo. Por padrão, o sed não altera o archivo original, apenas exibe o resultado da transformação."
          - "Observe que apenas a primeira ocorrência em cada linha é substituída. Se uma linha tiver mais de uma ocorrência de 'linux', apenas a primeira será alterada."
          - "**Substituição global e insensitiva a maiúsculas/minúsculas:**"
          - "Para substituir todas as ocorrências em cada linha, usamos a flag <code>g</code> (global). Para ignorar maiúsculas/minúsculas, usamos a flag <code>i</code> (insensitive):"
          - "`sed 's/linux/GIRUS/gi' archivo_ejemplo.txt`"
          - "Este comando substitui todas as ocorrências de 'linux' (independente da capitalização) por 'GIRUS' em todo o archivo."
          - "**Editando apenas linhas específicas:**"
          - "O sed também permite aplicar comandos apenas a linhas que correspondem a un padrão. Por ejemplo, vamos deletar todas as linhas que contêm a palavra 'sem':"
          - "`sed '/sem/d' archivo_ejemplo.txt`"
          - "Aqui, <code>/sem/</code> é un padrão de busca e <code>d</code> é o comando de deleção. Este comando remove completamente todas as linhas que contêm 'sem'."
          - "**Modificando múltiplas linhas:**"
          - "Podemos combinar várias operações usando múltiplos comandos separados por ponto e vírgula. Por ejemplo, vamos substituir 'linux' por 'GIRUS' e 'LINHA' por 'Registro':"
          - "`sed 's/linux/GIRUS/gi; s/LINHA/Registro/g' archivo_ejemplo.txt`"
          - "**Editando archivos no lugar:**"
          - "Por padrão, o sed não modifica o archivo original. Para salvar as alterações diretamente no archivo, usamos a flag <code>-i</code> (in-place):"
          - "`sed -i 's/linux/GIRUS/gi' archivo_ejemplo.txt`"
          - "Este comando modifica o archivo original diretamente. Em sistemas BSD como macOS, usted precisa fornecer uma extensão de backup: <code>sed -i '' 's/linux/GIRUS/gi' archivo_ejemplo.txt</code>"
          - "**Aplicando condicionais:**"
          - "Também podemos aplicar comandos apenas a linhas específicas por número. Por ejemplo, para substituir 'linux' por 'GIRUS' apenas na primeira linha:"
          - "`sed '1 s/linux/GIRUS/' archivo_ejemplo.txt`"
          - "Ou para substituir apenas nas linhas 1 a 3:"
          - "`sed '1,3 s/linux/GIRUS/g' archivo_ejemplo.txt`"
        tips:
          - type: "tip"
            title: "Sintaxe do sed"
            content: "A sintaxe básica para substituição é 's/padrão/substituição/flags'. Flags comuns: g (global, todas ocorrências), i (case-insensitive), p (print)."
          - type: "warning"
            title: "Backup antes de editar"
            content: "Ao usar a opção -i para editar archivos no lugar, é recomendável fazer un backup ou especificar uma extensão de backup (ex: `sed -i.bak`) para evitar perda acidental de dados."
          - type: "info"
            title: "Expressões regulares"
            content: "O sed supuerta expressões regulares básicas por padrão. Para usar expressões regulares estendidas (como `+`, `?`, etc.), use a opção -E ou -r dependendo da sua distribuição Linux."
        validation:
          - command: "sed 's/linux/GIRUS/gi' archivo_ejemplo.txt | grep -c 'GIRUS'"
            expectedOutput: "3"
            errorMessage: "A substituição com sed não parece ter funcionado corretamente. verifique a sintaxe do comando."

      - name: "Processando Colunas com awk"
        description: "Explore a linguagem de programação awk para processar e analisar dados estruturados em colunas, aprendendo a extrair, transformar e formatar informações específicas."
        steps:
          - "O **awk** é uma linguagem de programação completa, especializada no processamento de dados baseados em texto. Diferente do grep e sed, que funcionam principalmente com linhas inteiras, o awk é particularmente útil para processar dados estruturados em colunas ou campos."
          - "O nome 'awk' vem das iniciais de seus criadores: Alfred **A**ho, Peter **W**einberger e Brian **K**ernighan. Esta ferramenta tem capacidades avançadas para manipulação de dados, incluindo variáveis, funções, e estruturas condicionais."
          - "Para demonstrar o poder do awk, vamos crear un archivo com dados estruturados em colunas:"
          - "`for i in "col1 col2 col3" "val1 val2 val3" "xyz abc 123"; do echo $i >> archivo_colunas.txt; done`"
          - "Este archivo simula dados tabulares, com três colunas separadas por espaços."
          - "**Conceito fundamental: campos e registros**"
          - "No awk, cada linha do archivo é considerada un 'registro', e cada palavra (ou conjunto de caracteres separados por delimitadores) é un 'campo'. Por padrão, os campos são separados por espaços em branco (espaços ou tabs)."
          - "- O registro completo é referenciado como <code>$0</code>"
          - "- Os campos individuais são referenciados como <code>$1</code>, <code>$2</code>, <code>$3</code>, etc."
          - "- <code>$NF</code> refere-se ao último campo (NF = Number of Fields)"
          - "**Imprimindo campos específicos:**"
          - "O comando mais básico do awk é imprimir un ou mais campos de cada linha:"
          - "`awk '{print $1}' archivo_colunas.txt`"
          - "Este comando imprime apenas o primeiro campo (coluna) de cada linha."
          - "Para imprimir múltiplos campos com formatação customizada:"
          - "`awk '{print \"Coluna 1: \" $1, \"Coluna 3: \" $3}' archivo_colunas.txt`"
          - "Observe que o awk permite incluir texto literal entre aspas na saída."
          - "**Imprimindo o último campo:**"
          - "Para imprimir o último campo de cada linha, independentemente de quantos campos a linha tenha:"
          - "`awk '{print $NF}' archivo_colunas.txt`"
          - "A variável especial <code>NF</code> contém o número de campos da linha atual, então <code>$NF</code> se refere ao último campo."
          - "**Aplicando condições:**"
          - "O awk permite processar apenas linhas que atendam a certas condições. Por ejemplo, para imprimir apenas linhas onde o terceiro campo é 'val3':"
          - "`awk '$3 == \"val3\" {print $0}' archivo_colunas.txt`"
          - "Aqui, <code>$3 == \"val3\"</code> é uma condição que debe ser satisfeita para que o bloco de código entre chaves seja executado."
          - "**Usando separadores diferentes:**"
          - "Por padrão, o awk considera espaços em branco como separadores de campo. Podemos especificar un separador diferente com a opção <code>-F</code>. vamos crear un archivo CSV para demonstrar:"
          - "`for i in "Nome,Idade,Cidade" "João,35,São Paulo" "Maria,28,Rio de Janeiro" "Pedro,42,Belo Horizonte"; do echo $i >> archivo_csv.txt; done`"
          - "Agora podemos processar este archivo especificando a vírgula como separador:"
          - "`awk -F, '{print \"Nome: \" $1, \"Idade: \" $2}' archivo_csv.txt`"
          - "**Cálculos e variáveis:**"
          - "O awk supuerta operações matemáticas e variáveis. Por ejemplo, para calcular a média de idade no nosso archivo CSV:"
          - "`awk -F, 'NR>1 {sum+=$2; count++} END {print \"Média de idade: \" sum/count}' archivo_csv.txt`"
          - "Este comando mais complexo:"
          - "1. Usa <code>NR>1</code> para pular o cabeçalho (NR = Number of Record, o número da linha atual)"
          - "2. Para cada linha processada, adiciona o valor do segundo campo (<code>$2</code>, a idade) à variável <code>sum</code> e incrementa <code>count</code>"
          - "3. Quando o processamento termina (bloco <code>END</code>), calcula e imprime a média (sum/count)"
        tips:
          - type: "info"
            title: "awk para dados tabulares"
            content: "awk é poderoso para processar archivos CSV ou qualquer dado delimitado por espaços/tabs. Ele trata cada linha como un registro e cada palavra como un campo ($1, $2, ... $NF)."
          - type: "tip"
            title: "Blocos especiais BEGIN e END"
            content: "O awk permite definir blocos de código para serem executados antes de processar qualquer linha (BEGIN) e após processar todas as linhas (END), útil para inicializar variáveis ou imprimir resultados finais."
          - type: "warning"
            title: "Performance em grandes datasets"
            content: "Para processamento de grandes volumes de dados, considere ferramentas mais especializadas como pandas (Python) ou utilizar o GNU awk (gawk) que possui extensões que podem melhorar a performance."
        validation:
          - command: "awk '{print $1}' archivo_colunas.txt | head -n 1"
            expectedOutput: "col1"
            errorMessage: "O awk não parece estar imprimindo a primeira coluna corretamente."
          - command: "awk -F, 'NR>1 {sum+=$2} END {print sum}' archivo_csv.txt"
            expectedOutput: "105"
            errorMessage: "A soma das idades no archivo CSV não está correta. verifique se o archivo foi criado adequadamente." 
