apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-ec2-vpc-lab-es
  namespace: girus
  labels:
    app: girus-lab-template
data:
  lab.yaml: |
    name: aws-ec2-vpc-es
    title: "EC2 e VPC na AWS"
    description: "Aprenda a configurar e gerenciar instâncias EC2 e Virtual Private Cloud (VPC) na AWS. Este laboratório guiado explora conceitos fundamentais de computação em nuvem e networking na AWS."
    duration: 45m
    image: "linuxtips/girus-devops:0.1"
    privileged: true
    tasks:
      - name: "Criando uma VPC"
        description: "Aprenda a criar e configurar uma VPC na AWS."
        steps:
          - description: "Crie uma VPC com CIDR 10.0.0.0/16"
            command: "aws ec2 create-vpc --cidr-block 10.0.0.0/16 --tag-specifications 'ResourceType=vpc,Tags=[{Key=Name,Value=LabVPC}]'"
            expectedOutput: "VpcId"
            hint: "Use o comando aws ec2 create-vpc com --cidr-block"

          - description: "Crie subnets públicas e privadas"
            command: "aws ec2 create-subnet --vpc-id $(aws ec2 describe-vpcs --filters 'Name=tag:Name,Values=LabVPC' --query 'Vpcs[0].VpcId' --output text) --cidr-block 10.0.1.0/24 --availability-zone us-east-1a --tag-specifications 'ResourceType=subnet,Tags=[{Key=Name,Value=PublicSubnet1}]'"
            expectedOutput: "SubnetId"
            hint: "Use o comando aws ec2 create-subnet para criar subnets"

          - description: "Configure a tabela de rotas"
            command: "aws ec2 create-route-table --vpc-id $(aws ec2 describe-vpcs --filters 'Name=tag:Name,Values=LabVPC' --query 'Vpcs[0].VpcId' --output text) --tag-specifications 'ResourceType=route-table,Tags=[{Key=Name,Value=PublicRouteTable}]'"
            expectedOutput: "RouteTableId"
            hint: "Use o comando aws ec2 create-route-table para criar a tabela de rotas"

      - name: "Configurando Instâncias EC2"
        description: "Aprenda a criar e configurar instâncias EC2."
        steps:
          - description: "Crie um security group"
            command: "aws ec2 create-security-group --group-name LabSecurityGroup --description 'Security group for lab instances' --vpc-id $(aws ec2 describe-vpcs --filters 'Name=tag:Name,Values=LabVPC' --query 'Vpcs[0].VpcId' --output text)"
            expectedOutput: "GroupId"
            hint: "Use o comando aws ec2 create-security-group"

          - description: "Configure regras do security group"
            command: "aws ec2 authorize-security-group-ingress --group-id $(aws ec2 describe-security-groups --filters 'Name=group-name,Values=LabSecurityGroup' --query 'SecurityGroups[0].GroupId' --output text) --protocol tcp --port 22 --cidr 0.0.0.0/0"
            expectedOutput: "Return"
            hint: "Use o comando aws ec2 authorize-security-group-ingress"

          - description: "Lance uma instância EC2"
            command: "aws ec2 run-instances --image-id ami-0c55b159cbfafe1f0 --instance-type t2.micro --key-name MyKeyPair --security-group-ids $(aws ec2 describe-security-groups --filters 'Name=group-name,Values=LabSecurityGroup' --query 'SecurityGroups[0].GroupId' --output text) --subnet-id $(aws ec2 describe-subnets --filters 'Name=tag:Name,Values=PublicSubnet1' --query 'Subnets[0].SubnetId' --output text) --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=LabInstance}]'"
            expectedOutput: "InstanceId"
            hint: "Use o comando aws ec2 run-instances"

      - name: "Gerenciamento de Instâncias"
        description: "Aprenda a gerenciar e monitorar instâncias EC2."
        steps:
          - description: "Verifique o status da instância"
            command: "aws ec2 describe-instances --filters 'Name=tag:Name,Values=LabInstance' --query 'Reservations[0].Instances[0].State.Name' --output text"
            expectedOutput: "running"
            hint: "Use o comando aws ec2 describe-instances"

          - description: "Obtenha o endereço IP público"
            command: "aws ec2 describe-instances --filters 'Name=tag:Name,Values=LabInstance' --query 'Reservations[0].Instances[0].PublicIpAddress' --output text"
            expectedOutput: "\\d+\\.\\d+\\.\\d+\\.\\d+"
            hint: "Use o comando aws ec2 describe-instances para obter o IP"

          - description: "Monitore a utilização da CPU"
            command: "aws cloudwatch get-metric-statistics --namespace AWS/EC2 --metric-name CPUUtilization --dimensions Name=InstanceId,Value=$(aws ec2 describe-instances --filters 'Name=tag:Name,Values=LabInstance' --query 'Reservations[0].Instances[0].InstanceId' --output text) --start-time $(date -u +%Y-%m-%dT%H:%M:%SZ) --end-time $(date -u +%Y-%m-%dT%H:%M:%SZ) --period 300 --statistics Average"
            expectedOutput: "Datapoints"
            hint: "Use o comando aws cloudwatch get-metric-statistics"
